### ISSUE TITLE
About VisDrone2ReID dataset

### ISSUE THREAD

**Issue by wsw321** [dyhBUPT/GIAOTracker#1]
Sorry to bother you. Could the visdrone-2-reid dataset be open source?

**Comment by dyhBUPT** [comment]
I'm sorry, but it's a little hard for me to fine this code for now. 

I think the paper has a detailed description about the ReID dataset. So maybe you can generate the dataset by yourself.

**Comment by wsw321** [comment]
> I'm sorry, but it's a little hard for me to fine this code for now.
> 
> I think the paper has a detailed description about the ReID dataset. So maybe you can generate the dataset by yourself.

OK, I'll try. Thank you.
