### ISSUE TITLE
About ORB and RANSAC

### ISSUE THREAD

**Issue by s4k10503** [dyhBUPT/GIAOTracker#2]
Hi

Like GIAOTracker, Strong SORT also uses a camera motion compensation process.
However, GIAOTracker uses ORB + RANSAC, while Strong SORT uses ECC.
Why do they use different correction algorithms?
Is there any difference in performance between them?

Thanks.

**Comment by dyhBUPT** [comment]
It depends on the experimental results.
For StrongSORT on MOT17, we also try ORB but it underperforms ECC.
You can have a try.

**Comment by s4k10503** [comment]
Thanks for the quick response!
I understand that the reason is performance related.
If I have any more questions I will ask you.
